import Link from "next/link";

const features = [
  {
    name: "Dashboard & Workflow Table",
    location: "Demo → Dashboard tab",
    tryIt: "Use search box, status dropdown, and platform filter. Click any row to select a workflow. Click 'View runbook →' to jump to runbook view.",
    mocked: "All workflow data, stats, and chart values are hardcoded in mockData.ts. Filters run client-side on the static array.",
    production:
      "Supabase stores workflows synced from platform APIs. Stats computed from real usage events. Chart pulls from billing/analytics tables.",
  },
  {
    name: "Platform Connection (Make/Zapier/n8n)",
    location: "Demo → Connect tab, or 'Connect Platform' button in header",
    tryIt: "Click platform cards or '+ Add Connection' to open the 3-step OAuth wizard. Click 'Sync now' or 'Disconnect' on connected accounts. Drop zone accepts JSON imports.",
    mocked: "OAuth flow is simulated with a modal wizard. No real API calls. Connected accounts stored in React state.",
    production:
      "OAuth 2.0 for Make/Zapier (redirect to platform, store refresh tokens encrypted). n8n uses API key + base URL. JSON import parsed by serverless function into normalized node graph.",
  },
  {
    name: "AI-Generated Runbook",
    location: "Demo → Runbook tab",
    tryIt: "Navigate steps via sidebar or Previous/Next buttons. Click 'Regenerate' to simulate re-generation.",
    mocked: "6 pre-written runbook steps with screenshot descriptions. Step navigation is client-side state.",
    production:
      "OpenAI API receives normalized workflow JSON + platform context. Returns structured sections. Headless browser captures annotated screenshots of each node in the platform UI.",
  },
  {
    name: "Modular Node Breakdown",
    location: "Demo → Node Breakdown tab",
    tryIt: "Click node cards in the left panel to switch between HubSpot trigger, Clearbit enrichment, and Slack action nodes. View inputs, outputs, and failure modes.",
    mocked: "3 detailed node objects with realistic field names and failure scenarios. Selection updates the detail panel.",
    production:
      "Platform-specific adapters extract node config from workflow JSON. LLM generates failure mode analysis based on node type, API docs, and error handler configuration.",
  },
  {
    name: "PDF & Notion Export",
    location: "Demo → Export tab",
    tryIt: "Click PDF or Notion cards to open export modal. Toggle options, click 'Export Now' to see progress bar and toast confirmation. 'Download again' in history table.",
    mocked: "Export progress is a timed animation. No files generated. History table is static.",
    production:
      "PDF: Puppeteer renders runbook HTML to PDF with branding. Notion: API creates page with blocks for each section, embeds screenshots. Stripe metered billing for export credits.",
  },
  {
    name: "Change Detection & Re-documentation",
    location: "Demo → Change Detection tab",
    tryIt: "Filter by severity (all/major/critical). Click 'View diff' on any row. 'Queue Re-doc' and 'Run scan now' trigger toasts. Check re-doc status badges.",
    mocked: "5 change events with varied severity and status. Nightly scan schedule is static text.",
    production:
      "Vercel Cron at 22:00 UTC polls platform APIs for workflow version hashes. Diff engine detects node additions, config changes, connection updates. Changed workflows queued in serverless job queue for OpenAI re-processing.",
  },
  {
    name: "Billing & Credit Packs",
    location: "Demo → sidebar Billing toggle, header '+ Buy Credit' button",
    tryIt: "Toggle Starter/Growth plans in sidebar. Click '+ Buy Credit ($0.99)' to increment usage counter.",
    mocked: "Plan toggle and credit purchase update local state only. No Stripe integration.",
    production:
      "Stripe subscriptions for Starter ($29/5 workflows) and Growth ($79/20 workflows). Metered billing for $0.99 overage credits. Webhooks update Supabase usage counters.",
  },
  {
    name: "Activity Feed",
    location: "Demo → Dashboard tab, bottom section",
    tryIt: "Click any activity item to see a toast with the full message.",
    mocked: "8 static activity items with varied types (change, export, connect, generate, alert).",
    production:
      "Event stream from job queue, export service, and change detection cron. Real-time updates via Supabase realtime subscriptions.",
  },
  {
    name: "DEV NOTE Tooltips",
    location: "Throughout /demo — small 'i' icons beside major controls",
    tryIt: "Click any blue 'i' icon to open a tooltip explaining what the feature does and how it would work in production.",
    mocked: "Static tooltip content hardcoded in DevNote components.",
    production:
      "These tooltips are demo-only. In production, inline help links to AutoDoc's own documentation (generated by AutoDoc, naturally).",
  },
];

const architecture = [
  {
    step: "1. Ingest",
    detail: "User connects Make/Zapier/n8n or uploads JSON. Platform API returns workflow definition.",
  },
  {
    step: "2. Normalize",
    detail: "Serverless function maps platform-specific schema to internal node graph (nodes, edges, error handlers).",
  },
  {
    step: "3. Generate",
    detail: "OpenAI processes graph + platform context into structured runbook JSON (steps, node details, failure modes).",
  },
  {
    step: "4. Screenshot",
    detail: "Headless browser captures annotated UI screenshots for each node (optional, cached).",
  },
  {
    step: "5. Store & Serve",
    detail: "Runbook saved to Supabase. Rendered in dashboard. Available for PDF/Notion export.",
  },
  {
    step: "6. Monitor",
    detail: "Nightly cron diffs workflow versions. Changes trigger re-generation. Stripe bills accordingly.",
  },
];

export const metadata = {
  title: "Developer Documentation — AutoDoc",
  description: "Feature documentation for the AutoDoc interactive demo",
};

export default function DevelopersPage() {
  return (
    <div className="section-padding">
      <div className="mx-auto max-w-4xl">
        <div className="mb-12">
          <p className="mb-2 text-sm font-medium text-brand-400">For reviewers & implementers</p>
          <h1 className="mb-4 text-4xl font-bold text-white">Developer Documentation</h1>
          <p className="text-lg text-gray-400">
            Every feature in the{" "}
            <Link href="/demo" className="text-brand-400 hover:text-brand-300">
              interactive demo
            </Link>{" "}
            is documented below: what it does, where to click, what&apos;s mocked vs. production,
            and the intended data flow.
          </p>
        </div>

        <section className="mb-12">
          <h2 className="mb-6 text-2xl font-bold text-white">Architecture Overview</h2>
          <div className="space-y-4">
            {architecture.map((item) => (
              <div key={item.step} className="card flex gap-4 p-4">
                <span className="shrink-0 font-mono text-sm font-bold text-brand-400">
                  {item.step}
                </span>
                <p className="text-sm text-gray-300">{item.detail}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mb-12">
          <h2 className="mb-6 text-2xl font-bold text-white">Tech Stack (Production MVP)</h2>
          <div className="card p-6">
            <div className="grid gap-4 sm:grid-cols-2">
              {[
                { layer: "Frontend", tech: "Next.js 14 App Router + Tailwind" },
                { layer: "Database", tech: "Supabase (workflows, runbooks, users)" },
                { layer: "AI", tech: "OpenAI API (runbook generation)" },
                { layer: "Billing", tech: "Stripe (subscriptions + metered credits)" },
                { layer: "Cron", tech: "Vercel Cron (nightly change detection)" },
                { layer: "Support", tech: "Crisp AI chat (trained on product docs)" },
                { layer: "Export", tech: "Puppeteer (PDF) + Notion API" },
                { layer: "Integrations", tech: "Make REST API, Zapier API, n8n API" },
              ].map((item) => (
                <div key={item.layer}>
                  <p className="text-xs font-medium text-gray-500">{item.layer}</p>
                  <p className="text-sm text-gray-200">{item.tech}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section>
          <h2 className="mb-6 text-2xl font-bold text-white">Feature Reference</h2>
          <div className="space-y-6">
            {features.map((feature, i) => (
              <div key={feature.name} className="card p-6">
                <div className="mb-3 flex items-start justify-between gap-4">
                  <h3 className="text-lg font-semibold text-white">
                    {i + 1}. {feature.name}
                  </h3>
                  <span className="shrink-0 rounded bg-surface-700 px-2 py-0.5 font-mono text-xs text-gray-400">
                    {feature.location}
                  </span>
                </div>
                <div className="space-y-3 text-sm">
                  <div>
                    <p className="mb-1 font-medium text-brand-400">How to try it</p>
                    <p className="text-gray-300">{feature.tryIt}</p>
                  </div>
                  <div>
                    <p className="mb-1 font-medium text-amber-400">What&apos;s mocked</p>
                    <p className="text-gray-300">{feature.mocked}</p>
                  </div>
                  <div>
                    <p className="mb-1 font-medium text-emerald-400">Production implementation</p>
                    <p className="text-gray-300">{feature.production}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        <div className="mt-12 text-center">
          <Link href="/demo" className="btn-primary">
            Open Interactive Demo →
          </Link>
        </div>
      </div>
    </div>
  );
}
